---
name: Docker image
description: Creates a Docker image

inputs:
  workdir:
    description: Working Directory
    default: .
    required: false
  token:
    description: Github token
    required: true
  push:
    description: Push Images to GHCR
    required: false
    default: 'true'
  latest:
    description: Update latest tag
    required: false
    default: 'true'
  description:
    description: Container Image Description Label
    default: 'Built via Github Actions'
    required: false

runs:
  using: composite
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        labels: |
          org.opencontainers.image.description=${{ inputs.description }}
        flavor: |
          latest=${{inputs.latest}}
        tags: |
          type=ref,event=branch
          type=edge,enable=true,priority=700,prefix=,suffix=,branch=$repo.default_branch
          type=semver,pattern={{version}},prefix=v
          type=semver,pattern={{major}}.{{minor}},prefix=v
          type=semver,pattern={{major}},prefix=v,enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build and Push
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.workdir }}
        file: ${{inputs.workdir}}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        build-args: |
          VERSION=${{ steps.meta.outputs.version }}
          BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
